name: wheel-seminar-CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  cd:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          push: true
          tags: Odung2/wheel-seminar-cicd:${{github.sha}}, Odung2/wheel-seminar-cicd:latest
          platforms: linux/amd64, linux/arm64
